
//% color="#0082FC" icon="\uf293" block="PKS Controller"
namespace pkscontroller {

    // =================================
    // Globals

    let connected = false;
    let SEND_GLOBAL_LOCK = false;
    
    // Map to store callbacks for button press events
    let buttonCallbacks: { [buttonName: string]: () => void } = {};

    // parent -> [child1, child2, ...]
    let parentChildrenMap: { [parent: string]: string[] } = {};
    
    // parent.child -> value
    let statesMap: { [compositeKey: string]: string } = {};
    
    // parent -> component type (e.g., "B", "S", "TF", "J", "O")
    let componentTypesMap: { [componentName: string]: string } = {};
    
    // update the maps when the app sends data to microbit
    let updateMaps = (name: string, value: string): void => {
        let parentName = "";
        let actualChildName = "";
        let isFound = false;

        // Find the parent of the child (if exists)
        
        // Case A: 1 attribute components
        if (parentChildrenMap[name] && parentChildrenMap[name][0] === "value") {
            parentName = name;
            actualChildName = "value";
            isFound = true;
        } else {
            // Case B: many attriburtes components 
            let keys = Object.keys(parentChildrenMap);
            for (let i = 0; i < keys.length; i++) {
                let p = keys[i];
                if (parentChildrenMap[p].indexOf(name) !== -1) {
                    parentName = p;
                    actualChildName = name;
                    isFound = true;
                    break;
                }
            }
        }

        // Notes on value
        // Button/ToggleButton: [value]. 0 or 1
        // Slider: [value]. number belonging to [min, max]
        // TextField: [value]. value: string
        // Joystick: [angleName, strengthName]. angle: number, strength: number
        // Variable: [value]. value: number (any).

        // Derive key and update values
        let compositeKey = "";
        if (isFound) {
            compositeKey = parentName + "." + actualChildName;
        }

        if (isFound && compositeKey !== "") {
            statesMap[compositeKey] = value;
            if (componentTypesMap[parentName] === "Button") {
                // button always sends 1 when pressed 
                if (buttonCallbacks[parentName]) {
                    buttonCallbacks[parentName]();
                }
                // Auto-reset the button state to "0" after the event
                statesMap[compositeKey] = "0";
            }

        } else {
            console.error("Warning: Received unknown variable " + name);
        }

    }
    
    /**
     * Generates the parent-children map and initializes the states map
     * based on the provided configuration strings.
     * 
     * @param configs The config string generated by the program.
     */
    function generateMaps(configs: string[]): void {
        parentChildrenMap = {};
        statesMap = {};
        componentTypesMap = {};
        for (let i = 0; i < configs.length; i++) {
            let parts = configs[i].split(",");
            if (parts.length == 0) continue;
            
            let type = parts[0];
            
            if (type == "B" || type == "TB") {
                // Button or ToggleButton: B,name or TB,name
                if (parts.length >= 2) {
                    let parentName = parts[1];
                    let childName = "value"; 
                    parentChildrenMap[parentName] = [childName];
                    statesMap[parentName + "." + childName] = "0";
                    componentTypesMap[parentName] = "Button";
                } else {
                    console.error("Setup failed for Button/ToggleButton!");
                }
            } else if (type == "S") {
                // Slider: S,min,max,name
                if (parts.length >= 4) {
                    let parentName = parts[3];
                    let childName = "value";
                    parentChildrenMap[parentName] = [childName];
                    statesMap[parentName + "." + childName] = "0";
                    componentTypesMap[parentName] = "Slider";
                } else {
                    console.error("Setup failed for Slider");
                }
            } else if (type == "TF") {
                // TextField: TF,name
                if (parts.length >= 2) {
                    let parentName = parts[1];
                    // unify all 1-attribute components to have a child called "value" for consistency
                    let childName = "value";
                    parentChildrenMap[parentName] = [childName];
                    statesMap[parentName + "." + childName] = "";
                    componentTypesMap[parentName] = "TextField";
                } else {
                    console.error("Setup failed for TextField");
                }
            } else if (type == "J") {
                // Joystick: J,anglename,smax,strengthName,joystickName
                if (parts.length >= 5) {
                    let angleName = parts[1];
                    // TO CONFIRM: is smax returned??
                    let strengthName = parts[3];
                    let joystickName = parts[4];
                    
                    // joystick has 2 attributes, angleName and strengthName
                    parentChildrenMap[joystickName] = [angleName, strengthName];
                    statesMap[joystickName + "." + angleName] = "0";
                    statesMap[joystickName + "." + strengthName] = "0";
                    componentTypesMap[joystickName] = "Joystick";
                } else {
                    console.error("Setup failed for Joystick");
                }
            } else if (type == "O") {
                // Variables List: O,count,name1,plot1,name2,plot2...
                // each variable is logged as a parent.
                // Note: plotable is NOT changeable once initialized.
                if (parts.length >= 2) {
                    let count = parseInt(parts[1]);
                    for (let j = 0; j < count; j++) {
                        let nameIdx = 2 + (j * 2);
                        if (nameIdx < parts.length) {
                            let varName = parts[nameIdx];
                            parentChildrenMap[varName] = ["value"];
                            statesMap[varName + ".value"] = "0";
                            componentTypesMap[varName] = "Variable";
                        }
                    }
                } else {
                    console.error("Setup failed for Variables");
                }
            } else {
                console.error("Unknown config type: " + type);
            }
        }
    }

    /**
     * Checks if a variable name was actually defined in the configuration.
     */
    function isValidVariable(name: string): boolean {
        // Case A: only 1 data attribute
        if (parentChildrenMap[name] && parentChildrenMap[name][0] === "value") {
            return true;
        }
        
        // Case B: many data attributes
        let keys = Object.keys(parentChildrenMap);
        for (let i = 0; i < keys.length; i++) {
            if (parentChildrenMap[keys[i]].indexOf(name) !== -1) {
                return true;
            }
        }
        
        return false;
    }
    
    /**
     * Ensures a name is at most 15 characters long.
     * If it is longer, it truncates it to the first 15 characters.
     * @param name The name to sanitize
     */
    function sanitizeName(name: string): string {
        // the technical reason for this is because the bluetooth has a 60-byte buffer 
        // and we cannot allow names to be too long else we will have not enough space to receive data.
        // interestingly, i think it is only a receive buffer issue? but it is too much work (and quite difficult) to 
        // keep scraping for any data on uart receive. so we will use this as a workaround.
        if (name.length > 15) {
            return helpers.stringSlice(name, 0, 15);
        }
        return name;
    }
    
    // ========================================================================
    // Basic functions

    /**
     * Enable Bluetooth and set up the remote GUI application framework.
     * You must use this before using all the other bluetooth blocks
     */
    //% blockId=pkscontroller_bluetooth_setup block="setup bluetooth" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=99
    export function setupBluetooth(): void {

        bluetooth.startUartService();

        control.onEvent(DAL.MICROBIT_ID_BLE, DAL.MICROBIT_BLE_EVT_CONNECTED, function () {
            connected = true;
            basic.showLeds(`
                . . . . #
                . . . # .
                # . # . .
                . # . . .
                . . . . .
            `);
        });

        
        control.onEvent(DAL.MICROBIT_ID_BLE_UART, DAL.MICROBIT_UART_S_EVT_DELIM_MATCH, function () {
            
            // Read the data buffer up until the newline marker
            let receivedString = bluetooth.uartReadUntil(serial.delimiters(Delimiters.NewLine));
            console.log("got a message: " + receivedString);

            // Check if the message is a message from app
            if (receivedString && receivedString.indexOf("T,") === 0) {
                let parts = receivedString.split(",");
                
                // Ensure the string has at least the prefix and the parameter count
                if (parts.length >= 2) {
                    let numParams = parseInt(parts[1]);
                    
                    // Loop through each parameter pair
                    for (let i = 0; i < numParams; i++) {
                        // Calculate the array indices for the name and value
                        let nameIdx = 2 + (i * 2);
                        let valIdx = 3 + (i * 2);
                        
                        if (valIdx < parts.length) {
                            let pName = parts[nameIdx];
                            // .trim() removes any accidental trailing spaces or newline characters
                            let pValue = parts[valIdx].trim(); 
                            
                            // move stuff out of this function so no more cluttering
                            updateMaps(pName, pValue);
                        }
                    }
                }
            }
        });

        control.onEvent(DAL.MICROBIT_ID_BLE, DAL.MICROBIT_BLE_EVT_DISCONNECTED, function () {
            connected = false;
        });

    }

    /**
     * show the device name if it is not connected to bluetooth
     */
    //% blockId=pkscontroller_bluetooth_showdname block="display micro:bit name" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=98
    export function showDeviceName(): void {
        control.inBackground(() => {
            while (!connected) {
                basic.showString(control.deviceName())
                basic.pause(200)
            }
        })

    }

    /**
     * will tell you if microbit is connected to bluetooth or not
     */
    //% blockId=pkscontroller_bluetooth_connected block="bluetooth is connected" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=98
    export function isConnected(): boolean {
        return connected;
    }

    /**
     * wait until you are connected to bluetooth
     * blocks next block
     */
    //% blockId=pkscontroller_bluetooth_waitconn block="wait until bluetooth is connected" subcategory="Bluetooth"
    //% group="Bluetooth"
    //% weight=98
    export function waitUntilConnected(): void {
        while (!connected) {
            basic.pause(200)
        }
        console.log("done connected")
        // it actually takes like 1.4s for the connection to be stable 
        // so this exist to have a little buffer
        for (let i=0; i<10; i++) {
            console.log(`test send ${i}`)
            bluetooth.uartWriteLine("hi")
            basic.pause(200)
        }
    }

    /** =========================================
     *               CONFIGURATION
     *  =========================================
     *   This part deals with configuring the GUI on the app side. 
     *   Currently supports buttons, sliders, text fields, joysticks, and variables.
    **/ 

    /**
     * For configuring the GUI on app side.
     */



    /**
     * make configuration for GUI based on what you put in here.  
     * you must be connected to bluetooth!
     * @param configs The configuration list
     */
    // TODO: update subcategory in the future
    //% color="#f150f1"
    //% blockId=pkscontroller_bluetooth_makeconfig block="make configuration with $configs" subcategory="Bluetooth"
    //% configs.shadow="lists_create_with"
    //% configs.defl="pkscontroller_bluetooth_dummy"
    //% group="Configuration"
    //% weight=98
    export function makeConfiguration(configs: string[]): void {
        let config_string = `C,I,${configs.length},`
        if (configs.some(item => item.includes("O,"))) {
            config_string=`C,I,${configs.length-1},`
        }
        config_string += configs.join(",")
        config_string += "\n"

        // generate the maps based on configs
        generateMaps(configs)

        if (!connected) {
            basic.showIcon(IconNames.No);
            return;
        }

        console.log(`send data: ${config_string}`)
        // automatically determine how long the configs are
        bluetooth.uartWriteLine(config_string)
    }

    /**
     * Replace this with your own configuration!
     */
    //% color="#f150f1"
    //% blockId=pkscontroller_bluetooth_dummy block="dummy" subcategory="Bluetooth"
    //% group="Configuration"
    //% blockHidden=true 
    export function createDummy(): string {
        // Returns an empty string.
        // this is good cuz generateMaps() will ignore it
        return "";
    }

    /**
     * Creates a slider
     * @param min The minimum value of slider (>0), eg: 1
     * @param max The maximum value of slider (<=255), eg: 255
     * @param name The name of the slider
     */
    //% color="#f150f1"
    //% min.defl=0
    //% max.defl=255
    //% name.defl="Slider"
    //% blockId=pkscontroller_bluetooth_slider block="create slider $min $max $name" subcategory="Bluetooth"
    //% group="Configuration"
    export function createSlider(min: number, max: number, name: string): string {

        // silently change min/max if they are set to the wrong value
        if (min > max) {
            const temp = min
            min = max
            max = temp
        }
        const output: string = `S,${min},${max},${sanitizeName(name)}`
        return output

    }

    /**
     * Creates a button
     * @param name The name of the button
     */
    //% color="#f150f1"
    //% name.defl="Button"
    //% blockId=pkscontroller_bluetooth_button block="create button $name" subcategory="Bluetooth"
    //% group="Configuration"
    export function createButton(name: string): string {
        const output: string = `B,${sanitizeName(name)}`;
        return output;
    }

    /**
     * Creates a toggle button
     * @param name The name of the toggle button
     */
    //% color="#f150f1"
    //% name.defl="ToggleButton"
    //% blockId=pkscontroller_bluetooth_toggle_button block="create toggle button $name" subcategory="Bluetooth"
    //% group="Configuration"
    export function createToggleButton(name: string): string {
        const output: string = `TB,${sanitizeName(name)}`;
        return output;
    }

    /**
     * Creates a text field
     * @param name The name of the text field
     */
    //% color="#f150f1"
    //% name.defl="TextField"
    //% blockId=pkscontroller_bluetooth_textfield block="create text field $name" subcategory="Bluetooth"
    //% group="Configuration"
    export function createTextField(name: string): string {
        const output: string = `TF,${sanitizeName(name)}`;
        return output;
    }

    /**
     * Creates a joystick
     * @param anglename The name of the angle
     * @param smax The maximum value of the joystick
     * @param strengthName The name of the strength
     * @param joystickName The name of the joystick
     */
    //% color="#f150f1"
    //% anglename.defl="angle1"
    //% smax.min=0 smax.defl=255
    //% strengthName.defl="strength1"
    //% joystickName.defl="Joystick"
    //% blockId=pkscontroller_bluetooth_joystick block="create joystick $joystickName angle $anglename max strength $smax strength $strengthName" subcategory="Bluetooth"
    //% group="Configuration"
    export function createJoystick(anglename: string, smax: number, strengthName: string, joystickName: string): string {
        const output: string = `J,${sanitizeName(anglename)},${smax},${sanitizeName(strengthName)},${sanitizeName(joystickName)}`;
        return output;
    }

    /**
     * Creates a single variable configuration.
     * @param name The name of the variable
     * @param isPlotable Whether the variable is plotable
     */
    //% color="#a000a0"
    //% name.defl="var1"
    //% blockId=pkscontroller_bluetooth_var block="variable $name plotable $isPlotable" subcategory="Bluetooth"
    //% group="Configuration"
    export function createVariable(name: string, isPlotable: boolean): string {
        // Returns a formatted string for this variable
        return `${sanitizeName(name)},${isPlotable}`;
    }

    /**
     * A list of variables. You must wrap this around your variables, else they will not work.
     * @param vars The list of variable strings
     */
    //% color="#f150f1"
    //% blockId=pkscontroller_bluetooth_varlist block="variables $vars" subcategory="Bluetooth"
    //% group="Configuration"
    //% vars.shadow="lists_create_with"
    //% vars.defl="pkscontroller_bluetooth_var"
    export function formatVariablesList(vars: string[]): string {

        let output: string = `O,${vars.length}`;
        
        for (let i = 0; i < vars.length; i++) {
            output += `,${vars[i]}`;
        }
        
        return output;
    }

    /*
     * =========================================
     *                GETTERS
     * =========================================
     * For allowing the user to do stuff with the
     * data that is sent from the app to the microbit
     */



    /**
     * Check if a button or toggle button is currently pressed.
     * @param name The name of the button
     */
    //% blockId=pkscontroller_bluetooth_get_button_pressed
    //% block="button %name is pressed"
    //% color="#00A3A3"
    //% subcategory="Bluetooth"
    //% group="Values"
    //% weight=90
    export function isButtonToggled(name: string): boolean {
        // personal thoughts: it doesn't make sense for a button to be pressed
        // because the button is pressed for like 0.05ms and then released, so 
        // we should just have another block that checks if button "x" is pressed
        let val = statesMap[name + ".pressed"];
        // The app sends "1" for toggled/pressed and "0" for not pressed/toggled
        return val === "1";
    }

    /**
     * Get the current value of a slider.
     * @param name The name of the slider
     */
    //% blockId=pkscontroller_bluetooth_get_slider_value
    //% block="slider %name value"
    //% color="#00A3A3"
    //% subcategory="Bluetooth"
    //% group="Values"
    //% weight=89
    export function getSliderValue(name: string): number {
        let val = statesMap[name + ".value"];
        return parseFloat(val) || 0;
    }

    /**
     * Get the current text of a text field.
     * @param name The name of the text field
     */
    //% blockId=pkscontroller_bluetooth_get_textfield_value
    //% block="text field %name value"
    //% color="#00A3A3"
    //% subcategory="Bluetooth"
    //% group="Values"
    //% weight=88
    export function getTextFieldValue(name: string): string {
        return statesMap[name + ".text"] || "";
    }

    /**
     * Get the current angle of a joystick.
     * @param name The name of the joystick
     */
    //% blockId=pkscontroller_bluetooth_get_joystick_angle
    //% block="joystick %name angle"
    //% color="#00A3A3"
    //% subcategory="Bluetooth"
    //% group="Values"
    //% weight=87
    export function getJoystickAngle(name: string): number {
        // The first child of a joystick in our map is always the angle
        let children = parentChildrenMap[name];
        if (children && children.length > 0) {
            let val = statesMap[name + "." + children[0]];
            return parseFloat(val) || 0;
        }
        return 0;
    }

    /**
     * Get the current strength of a joystick.
     * @param name The name of the joystick
     */
    //% blockId=pkscontroller_bluetooth_get_joystick_strength
    //% block="joystick %name strength"
    //% color="#00A3A3"
    //% subcategory="Bluetooth"
    //% group="Values"
    //% weight=86
    export function getJoystickStrength(name: string): number {
        // The second child of a joystick in our map is always the strength
        let children = parentChildrenMap[name];
        if (children && children.length > 1) {
            let val = statesMap[name + "." + children[1]];
            return parseFloat(val) || 0;
        }
        return 0;
    }

    /**
     * Get the current value of a variable.
     * @param name The name of the variable
     */
    //% blockId=pkscontroller_bluetooth_get_variable_value
    //% block="variable %name value"
    //% color="#00A3A3"
    //% subcategory="Bluetooth"
    //% group="Values"
    //% weight=85
    export function getVariableValue(name: string): number {
        let val = statesMap[name + ".value"];
        return parseFloat(val) || 0;
    }

    // ========================================================================
    // Setters: For sending data from microbit to app
    // =======================================================================

    /**
     * Set value of a variable. Also update the value in the app correspondingly.
     * @param name The name of the variable
     * @param value The new value to send
     */
    //% blockId=pkscontroller_send_var_to_app
    //% block="set variable %name to %value "
    //% color="#FF8C00"
    //% group="Setters" subcategory="Bluetooth"
    //% weight=80
    export function sendVariableToApp(name: string, value: number): void {
        // Ensure we are connected and the variable is valid
        if (!connected) return;
        // dear friends, if you ever need to edit this please remember to
        // sanitize the raw input b y the user thanks
        name = sanitizeName(name);
        // console.log("looking at vname: " + name)
        if (!isValidVariable(name)) return;

        // Check the lock to prevent concurrent executions
        if (SEND_GLOBAL_LOCK) {
            return; 
        }
        SEND_GLOBAL_LOCK = true;

        // Format and send the message
        let message = `R,${name},${value}`;
        bluetooth.uartWriteLine(message);

        // Update internal data, also add delay
        updateMaps(name, value.toString());
        basic.pause(100);

        // Release the lock
        SEND_GLOBAL_LOCK = false;
    }

    /**
     * Set variable to true/false and update in the app correspondingly.
     * Note that true is (interpreted as) 1 and false is (interpreted as) 0.
     * @param name The name of the variable
     * @param value The boolean value to send
     */
    //% blockId=pkscontroller_send_bool_to_app
    //% block="set variable %name to %value"
    //% value.shadow="toggleYesNo"
    //% color="#FF8C00"
    //% group="Setters" subcategory="Bluetooth"
    //% weight=79
    export function sendBooleanToApp(name: string, value: boolean): void {
        
        let bvalue = value ? 1 : 0;
        
        sendVariableToApp(name, bvalue);
    }

    /**
     * Runs code when a button is pressed in the app.
     * The button state automatically resets to "not pressed" after the code runs.
     * @param name The name of the button
     * @param handler The code to run when the button is pressed
     */
    //% blockId=pkscontroller_on_button_pressed
    //% block="on button %name pressed"
    //% color="#FF8C00"
    //% group="Events" subcategory="Bluetooth"
    //% weight=95
    export function onButtonPressed(name: string, handler: () => void): void {
        name = sanitizeName(name);
        buttonCallbacks[name] = handler;
    }
}